# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('demand', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('throughput', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='depot_to_customer_shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('depot_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.depot')),
            ],
        ),
        migrations.CreateModel(
            name='factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='factory_to_customer_shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('factory_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factory')),
            ],
        ),
        migrations.CreateModel(
            name='factory_to_depots_shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('depot_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.depot')),
                ('factory_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='factory_to_depots_shipping',
            unique_together=set([('factory_fk', 'depot_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='factory_to_customer_shipping',
            unique_together=set([('factory_fk', 'customer_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='depot_to_customer_shipping',
            unique_together=set([('depot_fk', 'customer_fk')]),
        ),
    ]
