# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('demand', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='factory_shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('quantity', models.FloatField()),
                ('costumer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.costumer')),
                ('factory_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factory')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
