# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181127_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('troughput', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='factory_to_costumer_shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('quantity', models.FloatField()),
                ('costumer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.costumer')),
                ('factory_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factory')),
            ],
        ),
        migrations.CreateModel(
            name='factory_to_depots_shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('quantity', models.FloatField()),
                ('depot_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.depot')),
                ('factory_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factory')),
            ],
        ),
        migrations.RenameModel(
            old_name='factory_shipping',
            new_name='depot_to_costumer_shipping',
        ),
        migrations.RemoveField(
            model_name='depot_to_costumer_shipping',
            name='factory_fk',
        ),
        migrations.AddField(
            model_name='depot_to_costumer_shipping',
            name='depot_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.depot'),
            preserve_default=False,
        ),
    ]
