# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181127_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='costumer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='depot',
            old_name='troughput',
            new_name='throughput',
        ),
    ]
