# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181203_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot_to_costumer_shipping',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depot_to_costumer_shipping',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory_to_costumer_shipping',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory_to_costumer_shipping',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory_to_depots_shipping',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory_to_depots_shipping',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
