# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181203_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='depot_to_costumer_shipping',
            unique_together=set([('depot_fk', 'costumer_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='factory_to_costumer_shipping',
            unique_together=set([('factory_fk', 'costumer_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='factory_to_depots_shipping',
            unique_together=set([('factory_fk', 'depot_fk')]),
        ),
    ]
